<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yang Han">

<title>Problem_Set_3_Yang</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Problem_Set_3_Yang_files/libs/clipboard/clipboard.min.js"></script>
<script src="Problem_Set_3_Yang_files/libs/quarto-html/quarto.js"></script>
<script src="Problem_Set_3_Yang_files/libs/quarto-html/popper.min.js"></script>
<script src="Problem_Set_3_Yang_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Problem_Set_3_Yang_files/libs/quarto-html/anchor.min.js"></script>
<link href="Problem_Set_3_Yang_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Problem_Set_3_Yang_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Problem_Set_3_Yang_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Problem_Set_3_Yang_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Problem_Set_3_Yang_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem_Set_3_Yang</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yang Han </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>Link to Github repository:</p>
<section id="question-1" class="level1">
<h1>Question 1</h1>
<section id="part-a" class="level2">
<h2 class="anchored" data-anchor-id="part-a">Part a</h2>
<p>* Firstly, import the data and transfer them into stata format.</p>
<pre class="{#| code-fold: show}"><code>import sasxport5 "VIX_D.XPT"
save "VIX_D"
import sasxport5 "DEMO_D.XPT", clear</code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. import sasxport5 “VIX_D.XPT”</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. save “VIX_D”</p>
<p>file VIX_D.dta saved</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. import sasxport5 “DEMO_D.XPT”, clear</p>
<p>.</p>
<p>end of do-file</p>
<p>* Merge two files together and print out the total sample size.</p>
<pre class="{#| code-fold: show}"><code>merge 1:1 seqn using "VIX_D.dta", keep(match)
count</code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. merge 1:1 seqn using “VIX_D.dta”, keep(match)</p>
<p>Result Number of obs</p>
<p>-----------------------------------------</p>
<p>Not matched 0</p>
<p>Matched 6,980 (_merge==3)</p>
<p>-----------------------------------------</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. count</p>
<p>6,980</p>
<p>.</p>
<p>end of do-file</p>
<p>* We can see now the sample size now is 6980.</p>
</section>
<section id="part-b" class="level2">
<h2 class="anchored" data-anchor-id="part-b">Part b</h2>
<p>* Grouping each 10-year age bracket first.</p>
<pre class="{#| code-fold: show}"><code>egen age_group = cut(ridageyr), at(0(10)99)</code></pre>
<p>* Then create a table to check the number of people who wear glasses/contact lenses.</p>
<pre class="{#| code-fold: show}"><code>table (age_group) (viq220) (), missing statistic(proportion) nformat(%4.3f) </code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. egen age_group = cut(ridageyr), at(0(10)99)</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. table (age_group) (viq220) (), missing statistic(proportion) nformat(%4.3f)</p>
<p>-------------------------------------------------------------</p>
<p>| Glasses/contact lenses worn for distance</p>
<p>| 1 2 9 . Total</p>
<p>----------+--------------------------------------------------</p>
<p>age_group |</p>
<p>10 | 0.096 0.203 0.017 0.316</p>
<p>20 | 0.044 0.090 0.000 0.012 0.146</p>
<p>30 | 0.039 0.069 0.010 0.117</p>
<p>40 | 0.041 0.070 0.006 0.117</p>
<p>50 | 0.048 0.039 0.003 0.090</p>
<p>60 | 0.056 0.034 0.004 0.095</p>
<p>70 | 0.043 0.021 0.003 0.067</p>
<p>80 | 0.030 0.015 0.007 0.051</p>
<p>Total | 0.396 0.542 0.000 0.062 1.000</p>
<p>-------------------------------------------------------------</p>
<p>.</p>
<p>end of do-file</p>
<p>* From this table, the first column is the desired result, which is the proportion</p>
<p>* of those who wear glasses/contact lenses for distance vision.</p>
</section>
<section id="part-c" class="level2">
<h2 class="anchored" data-anchor-id="part-c">Part c</h2>
<p>* Remove missing values and don’t know values to ensure the response only has</p>
<p>* 2 logical values 1 and 2.</p>
<pre class="{#| code-fold: show}"><code>drop if viq220 == 9
drop if viq220 == .</code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. drop if viq220 == 9</p>
<p>(2 observations deleted)</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. drop if viq220 == .</p>
<p>(433 observations deleted)</p>
<p>.</p>
<p>end of do-file</p>
<p>* Then fit the regression models and remove observations with missing values</p>
<p>* in given predictors. Before fitting the model, we should replace viq220 with</p>
<p>* values 2 to 0. After fitting the models, get their AIC values.</p>
<p>* Model 1</p>
<pre class="{#| code-fold: show}"><code>drop if ridageyr == .
replace viq220 = 0 if viq220 == 2
logistic viq220 ridageyr
estat ic</code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. drop if ridageyr == .</p>
<p>(0 observations deleted)</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. replace viq220 = 0 if viq220 == 2</p>
<p>(3,780 real changes made)</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. logistic viq220 ridageyr</p>
<p>Logistic regression Number of obs = 6,545</p>
<p>LR chi2(1) = 443.37</p>
<p>Prob &gt; chi2 = 0.0000</p>
<p>Log likelihood = -4235.9433 Pseudo R2 = 0.0497</p>
<p>------------------------------------------------------------------------------</p>
<p>viq220 | Odds ratio Std. err. z P&gt;|z| [95% conf. interval]</p>
<p>-------------+----------------------------------------------------------------</p>
<p>ridageyr | 1.02498 .0012356 20.47 0.000 1.022561 1.027405</p>
<p>_cons | .283379 .0151461 -23.59 0.000 .2551952 .3146755</p>
<p>------------------------------------------------------------------------------</p>
<p>Note: _cons estimates baseline odds.</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. estat ic</p>
<p>Akaike’s information criterion and Bayesian information criterion</p>
<p>-----------------------------------------------------------------------------</p>
<p>Model | N ll(null) ll(model) df AIC BIC</p>
<p>-------------+---------------------------------------------------------------</p>
<p>. | 6,247 -4259.553 -4057.936 2 8119.871 8133.351</p>
<p>-----------------------------------------------------------------------------</p>
<p>Note: BIC uses N = number of observations. See [R] BIC note.</p>
<p>.</p>
<p>end of do-file</p>
<p>* Model 2</p>
<pre class="{#| code-fold: show}"><code>drop if ridreth1 == .
drop if riagendr == .
logistic viq220 ridageyr ridreth1 riagendr
estat ic</code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. drop if ridreth1 == .</p>
<p>(0 observations deleted)</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. drop if riagendr == .</p>
<p>(0 observations deleted)</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. logistic viq220 ridageyr ridreth1 riagendr</p>
<p>Logistic regression Number of obs = 6,545</p>
<p>LR chi2(3) = 564.76</p>
<p>Prob &gt; chi2 = 0.0000</p>
<p>Log likelihood = -4175.2478 Pseudo R2 = 0.0633</p>
<p>------------------------------------------------------------------------------</p>
<p>viq220 | Odds ratio Std. err. z P&gt;|z| [95% conf. interval]</p>
<p>-------------+----------------------------------------------------------------</p>
<p>ridageyr | 1.025324 .0012549 20.43 0.000 1.022867 1.027786</p>
<p>ridreth1 | 1.13275 .0254723 5.54 0.000 1.083909 1.183791</p>
<p>riagendr | 1.645628 .0866472 9.46 0.000 1.484271 1.824526</p>
<p>_cons | .0918421 .0109509 -20.02 0.000 .0727022 .1160209</p>
<p>------------------------------------------------------------------------------</p>
<p>Note: _cons estimates baseline odds.</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. estat ic</p>
<p>Akaike’s information criterion and Bayesian information criterion</p>
<p>-----------------------------------------------------------------------------</p>
<p>Model | N ll(null) ll(model) df AIC BIC</p>
<p>-------------+---------------------------------------------------------------</p>
<p>. | 6,247 -4259.553 -4000.785 4 8009.571 8036.53</p>
<p>-----------------------------------------------------------------------------</p>
<p>Note: BIC uses N = number of observations. See [R] BIC note.</p>
<p>.</p>
<p>end of do-file</p>
<p>* Model 3</p>
<pre class="{#| code-fold: show}"><code>drop if indfmpir == .
logistic viq220 ridageyr ridreth1 riagendr indfmpir
estat ic</code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. drop if indfmpir == .</p>
<p>(298 observations deleted)</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. logistic viq220 ridageyr ridreth1 riagendr indfmpir</p>
<p>Logistic regression Number of obs = 6,247</p>
<p>LR chi2(4) = 588.32</p>
<p>Prob &gt; chi2 = 0.0000</p>
<p>Log likelihood = -3965.3948 Pseudo R2 = 0.0691</p>
<p>------------------------------------------------------------------------------</p>
<p>viq220 | Odds ratio Std. err. z P&gt;|z| [95% conf. interval]</p>
<p>-------------+----------------------------------------------------------------</p>
<p>ridageyr | 1.024047 .0012924 18.83 0.000 1.021517 1.026583</p>
<p>ridreth1 | 1.097216 .0258548 3.94 0.000 1.047693 1.149079</p>
<p>riagendr | 1.679667 .0909057 9.58 0.000 1.510619 1.867631</p>
<p>indfmpir | 1.15327 .019618 8.38 0.000 1.115453 1.192368</p>
<p>_cons | .0717786 .0092205 -20.51 0.000 .0558023 .0923289</p>
<p>------------------------------------------------------------------------------</p>
<p>Note: _cons estimates baseline odds.</p>
<p>.</p>
<p>end of do-file</p>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. estat ic</p>
<p>Akaike’s information criterion and Bayesian information criterion</p>
<p>-----------------------------------------------------------------------------</p>
<p>Model | N ll(null) ll(model) df AIC BIC</p>
<p>-------------+---------------------------------------------------------------</p>
<p>. | 6,247 -4259.553 -3965.395 5 7940.79 7974.489</p>
<p>-----------------------------------------------------------------------------</p>
<p>Note: BIC uses N = number of observations. See [R] BIC note.</p>
<p>.</p>
<p>end of do-file</p>
</section>
<section id="part-d" class="level2">
<h2 class="anchored" data-anchor-id="part-d">Part d</h2>
<p>* We can tell that the odds of men and women being wears of glasess/contact</p>
<p>* lenses for distance vision differs. The odds ration of predictor riagendr</p>
<p>* is about 1.68, which means the odds of a woman (riagendr = 2) wearing glasses</p>
<p>* /contact lenses for distance vision are 1.6797 times higher than the odds of</p>
<p>* a man (riagendr = 1). Next, carry out a test to check whether the proportion</p>
<p>* of wearers of glasses/contact lenses for distance vision differs between</p>
<p>* men and women.</p>
<p>* Perform a test for Proportions</p>
<pre class="{#| code-fold: show}"><code>prtest viq220, by(riagendr)</code></pre>
<p>. do “C:\Users\86180\AppData\Local\Temp\STD5200_000000.tmp”</p>
<p>. prtest viq220, by(riagendr)</p>
<p>Two-sample test of proportions 1: Number of obs = 3053</p>
<p>2: Number of obs = 3194</p>
<p>------------------------------------------------------------------------------</p>
<p>Group | Mean Std. err. z P&gt;|z| [95% conf. interval]</p>
<p>-------------+----------------------------------------------------------------</p>
<p>1 | .3714379 .0087449 .3542983 .3885776</p>
<p>2 | .4762054 .0088371 .458885 .4935258</p>
<p>-------------+----------------------------------------------------------------</p>
<p>diff | -.1047675 .0124325 -.1291347 -.0804002</p>
<p>| under H0: .0125122 -8.37 0.000</p>
<p>------------------------------------------------------------------------------</p>
<p>diff = prop(1) - prop(2) z = -8.3732</p>
<p>H0: diff = 0</p>
<p>Ha: diff &lt; 0 Ha: diff != 0 Ha: diff &gt; 0</p>
<p>Pr(Z &lt; z) = 0.0000 Pr(|Z| &gt; |z|) = 0.0000 Pr(Z &gt; z) = 1.0000</p>
<p>.</p>
<p>end of do-file</p>
<p>* From the result we can see that the p-value is small, which means there are</p>
<p>* not enough evidence to accept the null. Therefore, we can conclude that the</p>
<p>* proportion differs between men and women.</p>
</section>
</section>
<section id="question-2" class="level1">
<h1>Question 2</h1>
<section id="part-a-1" class="level2">
<h2 class="anchored" data-anchor-id="part-a-1">Part a</h2>
<p>Firstly, import libraries and load the database.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DBI)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>sakila <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RSQLite<span class="sc">::</span><span class="fu">SQLite</span>(), <span class="st">"sakila_master.db"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(sakila)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "actor"                  "address"                "category"              
 [4] "city"                   "country"                "customer"              
 [7] "customer_list"          "film"                   "film_actor"            
[10] "film_category"          "film_list"              "film_text"             
[13] "inventory"              "language"               "payment"               
[16] "rental"                 "sales_by_film_category" "sales_by_store"        
[19] "staff"                  "staff_list"             "store"                 </code></pre>
</div>
</div>
<p>Use the database to answer the question.</p>
<div class="cell">
<details open="">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(sakila, <span class="st">"</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT l.name, COUNT(f.film_id) AS frequency</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM language AS l</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="st">    LEFT JOIN film AS f ON l.language_id = f.language_id</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE NOT l.name == 'English'</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY l.name</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY frequency DESC</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="st">    LIMIT 1</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      name frequency
1 Mandarin         0</code></pre>
</div>
</div>
<p>Since the frequencies of other languages are zero, we know that there is no second most common language for films.</p>
</section>
<section id="part-b-1" class="level2">
<h2 class="anchored" data-anchor-id="part-b-1">Part b</h2>
<section id="method-1" class="level3">
<h3 class="anchored" data-anchor-id="method-1">Method 1</h3>
<p>Join category, film_category and film into a single table.</p>
<div class="cell">
<details open="">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>result_tab_b <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(sakila, <span class="st">"</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="st">              SELECT *</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="st">              FROM (SELECT *</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM category AS c</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="st">                    LEFT JOIN film_category AS fc ON c.category_id = fc.category_id) AS cf</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="st">              LEFT JOIN film AS f ON cf.film_id = f.film_id</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Use R built-in functions to answer the question.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>most_comm <span class="ot">&lt;-</span> <span class="fu">table</span>(result_tab_b<span class="sc">$</span>name)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>answer_b <span class="ot">&lt;-</span> most_comm[<span class="fu">which.max</span>(most_comm)]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(answer_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sports 
    74 </code></pre>
</div>
</div>
</section>
<section id="method-2" class="level3">
<h3 class="anchored" data-anchor-id="method-2">Method 2</h3>
<div class="cell">
<details open="">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(sakila, <span class="st">"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT cf.name, COUNT(f.film_id) AS frequency</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM (SELECT *</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="st">          FROM category AS c</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="st">          LEFT JOIN film_category AS fc ON c.category_id = fc.category_id) AS cf</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="st">    LEFT JOIN film AS f ON cf.film_id = f.film_id</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY cf.name</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY frequency DESC</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="st">    LIMIT 1</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    name frequency
1 Sports        74</code></pre>
</div>
</div>
<p>From both methods we find that the most common genre is Sports, which are 74 movies of this genre.</p>
</section>
</section>
<section id="part-c-1" class="level2">
<h2 class="anchored" data-anchor-id="part-c-1">Part c</h2>
<section id="method-1-1" class="level3">
<h3 class="anchored" data-anchor-id="method-1-1">Method 1</h3>
<p>Join country, city, address and customer into a single table.</p>
<div class="cell">
<details open="">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>result_tab_c <span class="ot">&lt;-</span> <span class="fu">dbGetQuery</span>(sakila, <span class="st">"</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="st">              SELECT *</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="st">              FROM (SELECT *</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM (SELECT *</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="st">                          FROM country AS co</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="st">                          LEFT JOIN city AS ci ON co.country_id = ci.country_id) AS c</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    LEFT JOIN address AS ad ON c.city_id = ad.city_id) AS a</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="st">              LEFT JOIN customer AS cu ON a.address_id = cu.address_id</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Use R built-in functions to answer the question.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>counts <span class="ot">&lt;-</span> <span class="fu">table</span>(result_tab_c<span class="sc">$</span>country)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>answer_c <span class="ot">&lt;-</span> counts[counts <span class="sc">==</span> <span class="dv">9</span>]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(answer_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>United Kingdom 
             9 </code></pre>
</div>
</div>
</section>
<section id="method-2-1" class="level3">
<h3 class="anchored" data-anchor-id="method-2-1">Method 2</h3>
<div class="cell">
<details open="">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dbGetQuery</span>(sakila, <span class="st">"</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="st">              SELECT a.country, COUNT(cu.customer_id) AS frequency</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="st">              FROM (SELECT *</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="st">                    FROM (SELECT *</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="st">                          FROM country AS co</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="st">                          LEFT JOIN city AS ci ON co.country_id = ci.country_id) AS c</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="st">                    LEFT JOIN address AS ad ON c.city_id = ad.city_id) AS a</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="st">              LEFT JOIN customer AS cu ON a.address_id = cu.address_id</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a><span class="st">              GROUP BY a.country</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="st">              HAVING frequency == 9</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         country frequency
1 United Kingdom         9</code></pre>
</div>
</div>
<p>From both methods we find that only UK has exactly 9 customers.</p>
</section>
</section>
</section>
<section id="question-3" class="level1">
<h1>Question 3</h1>
<p>Download the data and import it into R.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>us_500 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"us-500.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="part-a-2" class="level2">
<h2 class="anchored" data-anchor-id="part-a-2">Part a</h2>
<p>Firstly, extract email from the data.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>email <span class="ot">&lt;-</span> us_500<span class="sc">$</span>email</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Then find the number and calculate the proportion.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>target_num_a <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">grep</span>(<span class="st">".net"</span>, email))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>net_prop <span class="ot">&lt;-</span> target_num_a <span class="sc">/</span> <span class="fu">length</span>(email)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(net_prop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.146</code></pre>
</div>
</div>
<p>We can see that the proportion of email addresses are hosted at a domain with TLD “.net” is 0.146, which is 14.6%.</p>
</section>
<section id="part-b-2" class="level2">
<h2 class="anchored" data-anchor-id="part-b-2">Part b</h2>
<p>The question is equivalent to find the proportion of email addresses that have at least 3 non alphanumeric characters in them since there will be expected “@” and “.” in all addresses. Remove all alphanumerics from the email addresses.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>non_alpnum <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"[A-Za-z0-9]"</span>, <span class="st">""</span>, email)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Calculate the proportion.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>non_alpnum_type <span class="ot">&lt;-</span> <span class="fu">table</span>(non_alpnum)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(non_alpnum_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>non_alpnum
.@.  @. _@. 
129 247 124 </code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>non_alpnum_prop <span class="ot">&lt;-</span> (<span class="dv">129</span> <span class="sc">+</span> <span class="dv">124</span>) <span class="sc">/</span> <span class="fu">sum</span>(non_alpnum_type)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(non_alpnum_prop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.506</code></pre>
</div>
</div>
<p>We can see that the proportion of email addresses have at least one non alphanumeric character is 0.506, which is 50.6%.</p>
</section>
<section id="part-c-2" class="level2">
<h2 class="anchored" data-anchor-id="part-c-2">Part c</h2>
<p>Firstly, extract all phone numbers from the data.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>phone_num <span class="ot">&lt;-</span> <span class="fu">cbind</span>(us_500<span class="sc">$</span>phone1, us_500<span class="sc">$</span>phone2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Extract the area code from the phone numbers and calculate the frequency.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>area_code <span class="ot">&lt;-</span> <span class="fu">substr</span>(phone_num, <span class="dv">1</span>, <span class="dv">3</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="fu">table</span>(area_code))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 36</code></pre>
</div>
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>freq <span class="ot">&lt;-</span> <span class="fu">table</span>(area_code)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Find the most common area code.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>most_comm_ac <span class="ot">&lt;-</span> freq[<span class="fu">which.max</span>(freq)]</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(most_comm_ac)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>973 
 36 </code></pre>
</div>
</div>
</section>
<section id="part-d-1" class="level2">
<h2 class="anchored" data-anchor-id="part-d-1">Part d</h2>
<p>Firstly, extract all addresses from the data.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>address <span class="ot">&lt;-</span> us_500<span class="sc">$</span>address</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Then extract all apartment numbers from the address.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>add_list <span class="ot">&lt;-</span> <span class="fu">strsplit</span>(address, <span class="st">"#"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>has_apt <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">sapply</span>(add_list, length) <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>c_apt_num <span class="ot">&lt;-</span> <span class="fu">sapply</span>(add_list[has_apt], <span class="cf">function</span>(x) x[<span class="dv">2</span>])</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>apt_num <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(c_apt_num)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Finally, take log of the apartment numbers and draw the histogram.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>log_apt_num <span class="ot">&lt;-</span> <span class="fu">log</span>(apt_num)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(log_apt_num, <span class="at">xlab =</span> <span class="st">"Log of Apt Number"</span>, <span class="at">main =</span> <span class="st">"Histogram of log of Apt Number"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Problem_Set_3_Yang_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="part-e" class="level2">
<h2 class="anchored" data-anchor-id="part-e">Part e</h2>
<p>To examine whether the apartment numbers appear to follow Benford’s law, we need the first digit of all the apartment numbers to follow a particular distribution defined by the law. The distribution: the leading digit d(d <span class="math inline">\(\in\)</span> {1, …, 9}) occurs with probability P(d) = log(1 + 1 / d), where log has a base 10. Check if the leading digit of the apartment numbers has this distribution.</p>
<p>Start with extracting the first digit from the apartment numbers.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>leading_digit <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">substr</span>(c_apt_num, <span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Then plot a histogram to compare with the distribution density plot.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(leading_digit, <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Histogram of the Data"</span>, <span class="at">xlab =</span> <span class="st">"Leading Digit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Problem_Set_3_Yang_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Generate the density plot of the distribution.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.301</span>, <span class="fl">0.176</span>, <span class="fl">0.125</span>, <span class="fl">0.097</span>, <span class="fl">0.079</span>, <span class="fl">0.067</span>, <span class="fl">0.058</span>, <span class="fl">0.051</span>, <span class="fl">0.046</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>leading <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(prob, <span class="at">names.arg =</span> leading, <span class="at">xlab =</span> <span class="st">"Leading Digit"</span>, <span class="at">ylab =</span> <span class="st">"PMF"</span>, <span class="at">main =</span> <span class="st">"Probability Mass Function Plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Problem_Set_3_Yang_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the two plots we can see that the difference between them is not trivial, which means the apartment number may not follow the Benford’s Law. However, since the sample is so small, it is hard to say that the data violates the law only based on these graphs. We can check the frequency table of the leading numbers.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(leading_digit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>leading_digit
 1  2  3  4  5  6  7  8  9 
11 11 12 11 14 10 12 11 17 </code></pre>
</div>
</div>
<p>We can see that 1-9 have similar frequencies, which means they are more likely to be uniformly distributed. Thus, I believe the apartment numbers would not pass as real data based on my common sense.</p>
</section>
<section id="part-f" class="level2">
<h2 class="anchored" data-anchor-id="part-f">Part f</h2>
<p>Firstly, extract all street numbers from the address.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>str_list <span class="ot">&lt;-</span> <span class="fu">strsplit</span>(address, <span class="st">" "</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>str_char <span class="ot">&lt;-</span> <span class="fu">sapply</span>(str_list, <span class="cf">function</span>(x) x[<span class="dv">1</span>])</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>str_num <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(str_char)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Then extracting the last digit from the street numbers.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>last_digit <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">substring</span>(str_char, <span class="fu">nchar</span>(str_char)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Plot a histogram to compare with the distribution density plot.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(last_digit, <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Histogram of the Data"</span>, <span class="at">xlab =</span> <span class="st">"Last Digit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Problem_Set_3_Yang_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Similarly, the last digit of street number also seems not following the Benford’s Law. Check the frequency table.</p>
<div class="cell">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(last_digit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>last_digit
 0  1  2  3  4  5  6  7  8  9 
39 41 54 51 53 52 43 56 45 66 </code></pre>
</div>
</div>
<p>However, the last digits of the street numbers do not follow the Benford’s Law of First digit semems reasonable. Since we should consider that if it follows a Benford’s Law of Last digit(if exists), we cannot just simply conclude that the street numbers are not real data. Actually it makes sense that the last digits have a uniform distribution just like the histogram shows.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>